openapi: 3.0.0
info:
  title: Leaf Agriculture Leaf API Reference > Alerts API Reference > Leaf Link > Provider Applications Info > Raven Slingshot API
  description: We are Leaf Agriculture, provider of a unified farm data API. After experiencing the difficulty of building applications in food and agriculture first hand as software developers, and hearing similar stories of frustration with existing tools and often insurmountable technical barriers from other companies, we decided to tackle the problem at hand.
  version: 1.0.0
tags:
- name: API Reference > Leaf Link > Provider Applications Info > Raven Slingshot
paths:
  /services/usermanagement/api/app-keys/RavenSlingshot:
    get:
      tags:
      - API Reference > Leaf Link > Provider Applications Info > Raven Slingshot
      summary: Leaf Agriculture Get all RavenSlingshot app information
      parameters:
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      - name: Authorization
        in: header
        schema:
          type: string
        example: Bearer {{leaf_token}}
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /services/usermanagement/api/app-keys/RavenSlingshot/{app_name}:
    get:
      tags:
      - API Reference > Leaf Link > Provider Applications Info > Raven Slingshot
      summary: Leaf Agriculture Get a RavenSlingshot app information
      parameters:
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      - name: Authorization
        in: header
        schema:
          type: string
        example: Bearer {{leaf_token}}
      - name: app_name
        in: path
        schema:
          type: string
        required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    post:
      tags:
      - API Reference > Leaf Link > Provider Applications Info > Raven Slingshot
      summary: Leaf Agriculture Create a RavenSlingshot app information
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                apiKey: '{{ravenslingshot_api_key}}'
                sharedSecret: '{{ravenslingshot_shared_secret}}'
      parameters:
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      - name: Authorization
        in: header
        schema:
          type: string
        example: Bearer {{leaf_token}}
      - name: app_name
        in: path
        schema:
          type: string
        required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    put:
      tags:
      - API Reference > Leaf Link > Provider Applications Info > Raven Slingshot
      summary: Leaf Agriculture Update a RavenSlingshot app information
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                apiKey: '{{ravenslingshot_api_key}}'
                sharedSecret: '{{ravenslingshot_shared_secret}}'
      parameters:
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      - name: Authorization
        in: header
        schema:
          type: string
        example: Bearer {{leaf_token}}
      - name: app_name
        in: path
        schema:
          type: string
        required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
      - API Reference > Leaf Link > Provider Applications Info > Raven Slingshot
      summary: Leaf Agriculture Delete a RavenSlingshot app information
      parameters:
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      - name: Authorization
        in: header
        schema:
          type: string
        example: Bearer {{leaf_token}}
      - name: app_name
        in: path
        schema:
          type: string
        required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
