openapi: 3.0.0
info:
  title: Leaf Agriculture Leaf API Reference > Alerts API Reference > Beta > Implements API
  description: We are Leaf Agriculture, provider of a unified farm data API. After experiencing the difficulty of building applications in food and agriculture first hand as software developers, and hearing similar stories of frustration with existing tools and often insurmountable technical barriers from other companies, we decided to tackle the problem at hand.
  version: 1.0.0
tags:
- name: API Reference > Beta > Implements
paths:
  /services/beta/api/users/{leaf_user_id}/implements:
    get:
      tags:
      - API Reference > Beta > Implements
      summary: Leaf Agriculture Get All Implements
      parameters:
      - name: Authorization
        in: header
        schema:
          type: string
        example: Bearer {{leaf_token}}
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      - name: leaf_user_id
        in: path
        schema:
          type: string
        required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /services/beta/api/users/{leaf_user_id}/implements/{implement_id}:
    get:
      tags:
      - API Reference > Beta > Implements
      summary: Leaf Agriculture Get An Implement
      parameters:
      - name: Authorization
        in: header
        schema:
          type: string
        example: Bearer {{leaf_token}}
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      - name: leaf_user_id
        in: path
        schema:
          type: string
        required: true
      - name: implement_id
        in: path
        schema:
          type: string
        required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
