openapi: 3.0.0
info:
  title: Leaf Agriculture Leaf API Reference > Alerts API Reference > Leaf User > Provider Credentials > Provider Organizations List API
  description: We are Leaf Agriculture, provider of a unified farm data API. After experiencing the difficulty of building applications in food and agriculture first hand as software developers, and hearing similar stories of frustration with existing tools and often insurmountable technical barriers from other companies, we decided to tackle the problem at hand.
  version: 1.0.0
tags:
- name: API Reference > Leaf User > Provider Credentials > Provider Organizations List
paths:
  /services/usermanagement/api/users/{leaf_user_id}/organizations/JohnDeere:
    get:
      tags:
      - API Reference > Leaf User > Provider Credentials > Provider Organizations List
      summary: Leaf Agriculture Get John Deere Organizations List
      parameters:
      - name: Authorization
        in: header
        schema:
          type: string
        example: Bearer {{leaf_token}}
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      - name: leaf_user_id
        in: path
        schema:
          type: string
        required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /services/usermanagement/api/users/{leaf_user_id}/organizations/Trimble:
    get:
      tags:
      - API Reference > Leaf User > Provider Credentials > Provider Organizations List
      summary: Leaf Agriculture Get Trimble Organizations List
      parameters:
      - name: Authorization
        in: header
        schema:
          type: string
        example: Bearer {{leaf_token}}
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      - name: leaf_user_id
        in: path
        schema:
          type: string
        required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
