openapi: 3.0.0
info:
  title: Leaf Agriculture Leaf API Reference > Alerts API Reference > Leaf User > Provider Credentials > Raven API
  description: We are Leaf Agriculture, provider of a unified farm data API. After experiencing the difficulty of building applications in food and agriculture first hand as software developers, and hearing similar stories of frustration with existing tools and often insurmountable technical barriers from other companies, we decided to tackle the problem at hand.
  version: 1.0.0
tags:
- name: API Reference > Leaf User > Provider Credentials > Raven
paths:
  /services/usermanagement/api/users/{leaf_user_id}/raven-credentials:
    get:
      tags:
      - API Reference > Leaf User > Provider Credentials > Raven
      summary: Leaf Agriculture Get Raven credentials of the LeafUser
      parameters:
      - name: Authorization
        in: header
        schema:
          type: string
        example: Bearer {{leaf_token}}
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      - name: leaf_user_id
        in: path
        schema:
          type: string
        required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    post:
      tags:
      - API Reference > Leaf User > Provider Credentials > Raven
      summary: Leaf Agriculture Add Raven credentials to the LeafUser
      requestBody:
        content:
          '*/*':
            schema:
              type: string
              example: '"{\n    \"clientId\": \"{{raven_client_id}}\",\n    \"clientSecret\": \"{{raven_client_secret}}\",\n    \"refreshToken\":  \"{{raven_refresh_token}}\"\n}"'
      parameters:
      - name: Authorization
        in: header
        schema:
          type: string
        example: Bearer {{leaf_token}}
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      - name: leaf_user_id
        in: path
        schema:
          type: string
        required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
      - API Reference > Leaf User > Provider Credentials > Raven
      summary: Leaf Agriculture Delete Raven credentials of the LeafUser
      parameters:
      - name: Authorization
        in: header
        schema:
          type: string
        example: Bearer {{leaf_token}}
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      - name: leaf_user_id
        in: path
        schema:
          type: string
        required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /services/usermanagement/api/users/{leaf_user_id}/raven-credentials/events:
    get:
      tags:
      - API Reference > Leaf User > Provider Credentials > Raven
      summary: Leaf Agriculture Get Raven credentials Events
      security:
      - bearerAuth: []
      parameters:
      - name: leaf_user_id
        in: path
        schema:
          type: string
        required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
