openapi: 3.0.0
info:
  title: Leaf Agriculture Leaf API Reference > Alerts API Reference > Leaf User > Provider Credentials > Agvance API
  description: We are Leaf Agriculture, provider of a unified farm data API. After experiencing the difficulty of building applications in food and agriculture first hand as software developers, and hearing similar stories of frustration with existing tools and often insurmountable technical barriers from other companies, we decided to tackle the problem at hand.
  version: 1.0.0
tags:
- name: API Reference > Leaf User > Provider Credentials > Agvance
paths:
  /services/usermanagement/api/users/{leaf_user_id}/agvance-credentials:
    get:
      tags:
      - API Reference > Leaf User > Provider Credentials > Agvance
      summary: Leaf Agriculture Get Agvance credentials from Leaf User
      parameters:
      - name: Authorization
        in: header
        schema:
          type: string
        example: Bearer {{leaf_token}}
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      - name: leaf_user_id
        in: path
        schema:
          type: string
        required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    post:
      tags:
      - API Reference > Leaf User > Provider Credentials > Agvance
      summary: Leaf Agriculture Add Agvance credentials to a Leaf User
      requestBody:
        content:
          '*/*':
            schema:
              type: string
              example: '"{\n  \"apiKey\": \"{{agvance_api_key}}\",\n  \"clientEnvironment\": \"STAGE or PRODUCTION\",\n  \"databaseId\": \"{{agvance_database_id}}\",\n  \"password\": \"{{agvance_password}}\",\n  \"username\": \"{{agvance_username}}\"\n}"'
      parameters:
      - name: Authorization
        in: header
        schema:
          type: string
        example: Bearer {{leaf_token}}
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      - name: leaf_user_id
        in: path
        schema:
          type: string
        required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
      - API Reference > Leaf User > Provider Credentials > Agvance
      summary: Leaf Agriculture Delete Agvance credentials from a Leaf User
      parameters:
      - name: Authorization
        in: header
        schema:
          type: string
        example: Bearer {{leaf_token}}
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      - name: leaf_user_id
        in: path
        schema:
          type: string
        required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /services/usermanagement/api/users/{leaf_user_id}/agvance-credentials/events:
    get:
      tags:
      - API Reference > Leaf User > Provider Credentials > Agvance
      summary: Leaf Agriculture Get Agvance credentials Events
      security:
      - bearerAuth: []
      parameters:
      - name: leaf_user_id
        in: path
        schema:
          type: string
        required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
