openapi: 3.0.0
info:
  title: Leaf Agriculture Leaf API Reference > Alerts API Reference > Providers Auth > Lindsay Auth API
  description: We are Leaf Agriculture, provider of a unified farm data API. After experiencing the difficulty of building applications in food and agriculture first hand as software developers, and hearing similar stories of frustration with existing tools and often insurmountable technical barriers from other companies, we decided to tackle the problem at hand.
  version: 1.0.0
tags:
- name: API Reference > Providers Auth > Lindsay Auth
paths:
  /lindsay/url:
    post:
      tags:
      - API Reference > Providers Auth > Lindsay Auth
      summary: Leaf Agriculture 1. Get Lindsay auth URL
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                clientId: '{{lindsay_client_id}}'
                redirectUri: '{{lindsay_redirect_uri}}'
                environment: STAGE
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /lindsay/token:
    post:
      tags:
      - API Reference > Providers Auth > Lindsay Auth
      summary: Leaf Agriculture 2. Get Lindsay Token
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                clientId: '{{lindsay_client_id}}'
                clientSecret: '{{lindsay_client_secret}}'
                redirectUri: '{{lindsay_redirect_uri}}'
                responseUrl: '{{lindsay_response_url}}'
                codeVerifier: '{{lindsay_code_verifier}}'
                environment: STAGE
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
